<a href="https://colab.research.google.com/github/tuyendq/lthwnumpy/blob/main/intro_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdcution to Numpy

In [ ]:
import numpy as np

In [ ]:
def randomization(n):
  """
  Arg:
    n - an integer
  Returns:
    A - a randomly-generated nx1 Numpy array
  """
  return np.random.random([n, 1])

In [ ]:
A = randomization(4)
print(A)

[[0.62993751]
 [0.60547575]
 [0.22169497]
 [0.36874059]]


In [ ]:
def operations(h, w):
  """
  Takes two inputs, h and w, and makes two Numpy array A and B of size h x w, and returns A, B, and s, the sum of A and B

  Arg:
    h - an integer - the height of A and B
    w - an integer - the width of A and B
  Returns (in this order):
    A - randomly-generated h x w Numpy array
    B - randomly-generated h x w Numpy array
  """
  A = np.random.random([h, w])
  B = np.random.random([h, w])
  s = A + B

  return (A, B, s)


In [ ]:
operations(4, 5)

(array([[0.68554974, 0.21143332, 0.27042203, 0.29866431, 0.70541654],
        [0.16403041, 0.42851921, 0.70510279, 0.47621181, 0.16631278],
        [0.9736085 , 0.33688972, 0.25610121, 0.10393359, 0.64941475],
        [0.18591349, 0.02704125, 0.40372812, 0.92893814, 0.84420679]]),
 array([[0.70223191, 0.78715936, 0.51947019, 0.42629284, 0.38722933],
        [0.28638497, 0.73522253, 0.75795493, 0.31434958, 0.19502372],
        [0.39640139, 0.14714165, 0.56741553, 0.88000073, 0.22932258],
        [0.11222921, 0.33070841, 0.78805321, 0.99352925, 0.38503425]]),
 array([[1.38778166, 0.99859268, 0.78989222, 0.72495714, 1.09264586],
        [0.45041538, 1.16374174, 1.46305772, 0.7905614 , 0.36133649],
        [1.37000989, 0.48403136, 0.82351674, 0.98393432, 0.87873733],
        [0.2981427 , 0.35774966, 1.19178133, 1.92246739, 1.22924104]]))

In [ ]:
def norm(A, B):
  """
  Takes two Numpy column arrays, A and B, and returns the L2 norm of their sum

  Arg:
    A - a Numpy array
    B - a Numpy array
  Returns:
    s - the L2 norm of A + B
  Ref: https://machinelearningmastery.com/vector-norms-machine-learning/
  """
  return np.linalg.norm(A + B)

In [ ]:
A = np.array([2, 4])
B = np.array([1, 5])
norm(A, B)

9.486832980505138

## Neural Network

In [ ]:
def neural_network(inputs, weights):
  """
    Take an input vector and runs it through a 1-layer neural network
    with a given weight matrix and returns the output.

    Arg:
      inputs: 2 x 1 Numpy array
      weights: 2 x 1 Numpy array
    Returns (in this order):
      out: a 1 x 1 Numpy array, representing the output of the neural network
  """
  # raise Notimplemented Error
  wT = np.transpose(weights)
  prod = np.matmul(wT, inputs)
  out = np.tanh(prod)
  return (out)